using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated0;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaConceptPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaConceptPageVM), nameof(EncyclopediaConceptPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaConceptPageVM.SetAttributes))]
    internal class EncyclopediaConceptPage
    {

        [HarmonyPostfix]
		static void Postfix(ref EncyclopediaConceptPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaConceptPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
}
