using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate), nameof(EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetAttributes))]
    internal class EncyclopediaHomePage
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = 1040f;
            ____widget_0.SuggestedWidth = 460f;
        }
    }
}
