using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated0;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_List_EncyclopediaListVM), nameof(EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_List_EncyclopediaListVM.SetAttributes))]
    internal class EncyclopediaListPage
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_List_EncyclopediaListVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
}
