using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated0;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM), nameof(EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM.SetAttributes))]
    internal class EncyclopediaHeroPage
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
}
