using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaClanPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM), nameof(EncyclopediaClanPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM.SetAttributes))]
    internal class EncyclopediaClanPage
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaClanPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
}
