using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated0;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Encyclopedia;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaBar__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaNavigatorVM), nameof(EncyclopediaBar__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaNavigatorVM.SetAttributes))]
    internal class EncyclopediaFullScreen
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaBar__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaNavigatorVM __instance, ref Widget ____widget_1, ref EncyclopediaSearchBarBrushWidget ____widget_3, ref Widget ____widget_6)
        {
            ____widget_1.SuggestedHeight = 1440;
            ____widget_1.SuggestedWidth = 2600;
            ____widget_3.MarginLeft = 2000f;
            ____widget_3.MarginBottom = 1200f;
            ____widget_6.VerticalAlignment = VerticalAlignment.Top;
            ____widget_6.HorizontalAlignment = HorizontalAlignment.Right;
            ____widget_6.PositionYOffset = 0f;
            ____widget_6.MarginLeft = 0f;

        }
    }
    [HarmonyPatch(typeof(EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate), nameof(EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate.SetAttributes))]
    internal class EncyclopediaHomePage
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM_Dependency_1_ItemTemplate __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = 1040f;
            ____widget_0.SuggestedWidth = 460f;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_List_EncyclopediaListVM), nameof(EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_List_EncyclopediaListVM.SetAttributes))]
    internal class EncyclopediaListPage
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_List_EncyclopediaListVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaSettlementPageVM), nameof(EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaSettlementPageVM.SetAttributes))]
    internal class EncyclopediaSettlementsPage
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaItemList__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaSettlementPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaUnitPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaUnitPageVM), nameof(EncyclopediaUnitPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaUnitPageVM.SetAttributes))]
    internal class EncyclopediaUnitPage
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaUnitPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaUnitPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM), nameof(EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM.SetAttributes))]
    internal class EncyclopediaHeroPage
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaFactionPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM), nameof(EncyclopediaFactionPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM.SetAttributes))]
    internal class EncyclopediaFactionPage
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaFactionPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaFactionPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaConceptPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaConceptPageVM), nameof(EncyclopediaConceptPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaConceptPageVM.SetAttributes))]
    internal class EncyclopediaConceptPage
    {

        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaConceptPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaConceptPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
    [HarmonyPatch(typeof(EncyclopediaClanPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM), nameof(EncyclopediaClanPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM.SetAttributes))]
    internal class EncyclopediaClanPage
    {
        [HarmonyPostfix]
        static void Postfix(ref EncyclopediaClanPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaClanPageVM __instance, ref Widget ____widget_0)
        {
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0.SuggestedHeight = res.Y - 280f;
            ____widget_0.SuggestedWidth = res.X - 40f;
            ____widget_0.VerticalAlignment = VerticalAlignment.Bottom;
        }
    }
}
